# Check user ldap_user is in organization ldap_org
- hosts: localhost
  vars:
    # ldap_user: user8
    # ldap_org: prod
    # ldap_server_url: 'ldap://192.168.122.104:8389'
  tasks:
    # Use fail state of command to provide continuation or halt inside a workflow task
    - name: Use ldapsearch to fail if user is not in organization
      ansible.builtin.command:
        cmd: ldapsearch -x -H {{ ldap_server_url }} -b uid={{ ldap_user }},ou={{ ldap_org }},dc=example,dc=org -D "cn=admin,dc=example,dc
=org" -w admin
