- hosts: localhost
  gather_facts: false
  tasks: 
    - name: Get facts for all subscriptions, including ones that are disabled.
      azure.azcollection.azure_rm_subscription_info:
        all: true
      delegate_to: localhost
      
