- hosts: localhost
  tasks:
    - name: Install packaging
      ansible.builtin.pip:
        name: packaging
    - name: Get facts for all subscriptions, including ones that are disabled.
      azure.azcollection.azure_rm_subscription_info:
        all: true
