- hosts: localhost
  gather_facts: false
  tasks: 
    - name: Get facts for all subscriptions, including ones that are disabled.
      azure.azcollection.azure_rm_subscription_info:
        client_id: "{{ client_id }}"
        password: "{{ secret }}"
        tenant: "{{ tenant }}"
        all: true
      delegate_to: localhost
      
