- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install packaging
      ansible.builtin.pip:
        executable: /usr/bin/pip3.9
        requirements: /home/runner/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
        state: installed
      delegate_to: localhost
      
    - name: Get facts for all subscriptions, including ones that are disabled.
      azure.azcollection.azure_rm_subscription_info:
        all: true
      delegate_to: localhost
      
