- hosts: localhost
  gather_facts: false
  vars:
    # Some variables are always present and by removing them we guarantee we're 
    # left with only actual extra vars passed.
    stock_variables: >-
      [ 
      "ansible_diff_mode", 
      "groups",
      "tower_job_template_id",
      "tower_inventory_name",
      "tower_user_last_name",
      "awx_user_name",
      "awx_job_id",
      "ansible_facts",
      "group_names",
      "inventory_hostname",
      "remote_tower_id",
      "inventory_dir",
      "ansible_check_mode",
      "ansible_version",
      "playbook_dir",
      "awx_job_template_name",
      "awx_inventory_name",
      "tower_user_id",
      "awx_user_last_name",
      "awx_user_first_name",
      "tower_job_id",
      "awx_job_launch_type",
      "anothervariable",
      "onelocalvariable",
      "remote_host_id",
      "remote_host_enabled",
      "inventory_file",
      "ansible_verbosity",
      "ansible_run_tags",
      "ansible_skip_tags",
      "ansible_inventory_sources",
      "ansible_forks",
      "ansible_config_file",
      "awx_execution_node",
      "tower_job_template_name",
      "tower_project_scm_branch",
      "awx_project_revision",
      "tower_inventory_id",
      "tower_user_first_name",
      "tower_user_email",
      "awx_user_id",
      "tower_job_launch_type",
      "remote_tower_enabled",
      "omit",
      "ansible_playbook_python",
      "tower_execution_node",
      "awx_job_template_id",
      "tower_project_revision",
      "awx_project_scm_branch",
      "awx_inventory_id",
      "tower_user_name",
      "awx_user_email",
      "inventory_hostname_short",
      "ansible_connection",
      "ANSIBLE_HOST_KEY_CHECKING",
      "RUNNER_ONLY_FAILED_EVENTS",
      "ANSIBLE_PARAMIKO_RECORD_HOST_KEYS",
      "_",
      "AWX_ISOLATED_DATA_DIR",
      "HOSTNAME",
      "MAX_EVENT_RES",
      "AWX_HOST",
      "ANSIBLE_UNSAFE_WRITES",
      "DESCRIPTION",
      "container",
      "INVENTORY_ID",
      "PROJECT_REVISION",
      "ANSIBLE_SSH_CONTROL_PATH_DIR",
      "AWX_PRIVATE_DATA_DIR",
      "PWD",
      "HOME",
      "LC_CTYPE",
      "ANSIBLE_RETRY_FILES_ENABLED",
      "ANSIBLE_ROLES_PATH",
      "ANSIBLE_STDOUT_CALLBACK",
      "ANSIBLE_INVENTORY_UNPARSED_FAILED",
      "ANSIBLE_COLLECTIONS_PATH",
      "ANSIBLE_COLLECTIONS_PATHS",
      "TERM",
      "RUNNER_OMIT_EVENTS",
      "JOB_ID",
      "ANSIBLE_FORCE_COLOR",
      "SHLVL",
      "ANSIBLE_CALLBACK_PLUGINS",
      "PATH"
      ]
  environment: "{{ dict( (key, value) for key, value in hostvars[inventory_hostname].items() if key not in stock_variables )  }}"
  tasks:
    - name: Get environment
      ansible.builtin.command:
        cmd: printenv
      register: _
      
    - name: Print environment
      ansible.builtin.debug:
        var: _.stdout_lines

      
