- hosts: localhost
  gather_facts: false
  environment: "{{ hostvars[inventory_hostname] }}"
  tasks:
    - name: Get environment
      ansible.builtin.command:
        cmd: printenv
      register: _
      
    - name: Print environment
      ansible.builtin.debug:
        var: "{{ _.stdout_lines }}"

      
