---
- name: Registering system with username and password
  hosts: all
  vars:
    rhc_auth:
      login:
        username: "{{ console_username }}"
        password: "{{ console_password }}"
  roles:
    - role: redhat.rhel_system_roles.rhc
