- name: Report on one VM
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get an existing VirtualMachine
      redhat.openshift_virtualization.kubevirt_vm_info:
         name: "{{ machine_name }}"
      register: default_testvm

    - name: Print VM info
      ansible.builtin.debug:
        var: default_testvm
  
