---
- name: Listen for events on a webhook
  hosts: localhost
  sources:
    - eda.builtin.webhook:
        host: 0.0.0.0
        port: 7000
 ## Define rules with conditions and actions
  rules:
    - name: Always debug
      condition: true
      action: 
        print_event:
          pretty: true        
